model_config:
  task: state_prediction

  glm_tokenizer_path: /data/models/SoulX-Duplug-0.6B/glm-4-voice-tokenizer
  enable_lora: true
  lora_r: 32
  lora_alpha: 64

  model_name: /data/models/SoulX-Duplug-0.6B/Qwen3-0.6B-expand_vocab_v2
  llm_dim: 1024
  init_ckpt_path_lora: /data/models/SoulX-Duplug-0.6B/SoulX-Duplug/SoulX-Duplug-0.6B-Bilingual.pth

infer_config:
  seed: 42
  device: cuda
  precision: bf16
  max_wait_num: 8
  max_mistake_num: 3
  far_field_threshold: 0.02
  developer_mode: false

  input:
    chunk_size: 2560
    audio_back_size: 15360
    audio_ahead_size: 640
    sample_rate: 16000

  asr:
    model_name: paraformer
    # model_name: sensevoice
    # language: en
